name: Generate Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  call-central-changelog:
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    uses: AIgorLabs/.github/.github/workflows/reusable-generate-changelog.yml@main
    secrets: inherit
